# ===================================================================
# Database Configuration (PostgreSQL Cloud Link)
# ===================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===================================================================
# Caching Configuration (Live Redis Cloud Instance)
# ===================================================================
spring.data.redis.host=redis-17312.crce276.ap-south-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=17312
spring.data.redis.password=EYRgWhl4uVChIsSyVHLoq4dZk9ZATQfC

# ===================================================================
# Security Token Configurations
# ===================================================================
jwt.secret=${JWT_SECRET_KEY}